# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogo-pin-config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogo-pin-config.proto',
  package='pogo_pin_board',
  syntax='proto2',
  serialized_pb=_b('\n\x15pogo-pin-config.proto\x12\x0epogo_pin_board\";\n\x0cPogoPinBoard\x12\x0c\n\x04uuid\x18\x01 \x01(\x0c\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POGOPINBOARD = _descriptor.Descriptor(
  name='PogoPinBoard',
  full_name='pogo_pin_board.PogoPinBoard',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='pogo_pin_board.PogoPinBoard.uuid', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='pogo_pin_board.PogoPinBoard.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='pogo_pin_board.PogoPinBoard.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['PogoPinBoard'] = _POGOPINBOARD

PogoPinBoard = _reflection.GeneratedProtocolMessageType('PogoPinBoard', (_message.Message,), dict(
  DESCRIPTOR = _POGOPINBOARD,
  __module__ = 'pogo_pin_config_pb2'
  # @@protoc_insertion_point(class_scope:pogo_pin_board.PogoPinBoard)
  ))
_sym_db.RegisterMessage(PogoPinBoard)


# @@protoc_insertion_point(module_scope)
